simulation:
  max_random_draws: 100000
  first_arrival_time: 2.0
  random_seed: 42

arrivals:
  inter_arrival_min: 2.0
  inter_arrival_max: 4.0
  destination_station: 1

stations:
  - id: 1
    name: "Station 1"
    servers: 1
    capacity: -1  # -1 means infinite capacity
    service_time_min: 1.0
    service_time_max: 2.0
    routing:
      - destination: 2
        probability: 0.8
      - destination: 3
        probability: 0.2

  - id: 2
    name: "Station 2"
    servers: 2
    capacity: 5
    service_time_min: 4.0
    service_time_max: 6.0
    routing:
      - destination: 1
        probability: 0.3
      - destination: 3
        probability: 0.5
      - destination: -1  # -1 means exit the system
        probability: 0.2

  - id: 3
    name: "Station 3"
    servers: 2
    capacity: 10
    service_time_min: 5.0
    service_time_max: 15.0
    routing:
      - destination: 2
        probability: 0.7
      - destination: -1  # -1 means exit the system
        probability: 0.3
